param(
    [string]$ProjectDir = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path,
    [string]$GradleUserHome = (Join-Path $env:USERPROFILE ".gradle")
)

$ErrorActionPreference = "Stop"

$moduleRoot = Join-Path $GradleUserHome "caches/modules-2/files-2.1/com.composables"
$aar = Get-ChildItem -Path $moduleRoot -Recurse -Filter "icons-lucide*.aar" |
    Sort-Object LastWriteTime -Descending |
    Select-Object -First 1

if (-not $aar) {
    throw "Unable to find icons-lucide AAR in Gradle cache. Run Gradle once to resolve com.composables:icons-lucide."
}

Add-Type -AssemblyName System.IO.Compression.FileSystem

$tempJar = Join-Path $env:TEMP "icons-lucide-classes.jar"
$aarZip = [IO.Compression.ZipFile]::OpenRead($aar.FullName)
try {
    $classesEntry = $aarZip.Entries | Where-Object { $_.FullName -eq "classes.jar" } | Select-Object -First 1
    if (-not $classesEntry) {
        throw "classes.jar not found in $($aar.FullName)"
    }
    [IO.Compression.ZipFileExtensions]::ExtractToFile($classesEntry, $tempJar, $true)
}
finally {
    $aarZip.Dispose()
}

$classZip = [IO.Compression.ZipFile]::OpenRead($tempJar)
try {
    $iconNames = $classZip.Entries |
        Where-Object {
            $_.FullName -like "com/composables/icons/lucide/*Kt.class" -and
            $_.FullName -notmatch '\$'
        } |
        ForEach-Object {
            [IO.Path]::GetFileNameWithoutExtension($_.FullName) -replace "Kt$", ""
        } |
        Where-Object { $_ -notin @("Lucide", "LucideIcon") } |
        Sort-Object -Unique
}
finally {
    $classZip.Dispose()
}

if (-not $iconNames -or $iconNames.Count -eq 0) {
    throw "No Lucide icon classes found in $($aar.FullName)"
}

$targetDir = Join-Path $ProjectDir "app/src/main/java/com/ithing/mobile/presentation/feature/dashboard"
$targetFile = Join-Path $targetDir "DashboardLucideIconRegistry.kt"

$entries = $iconNames | ForEach-Object {
    $key = $_.ToLowerInvariant()
    "    `"$key`" to Lucide.$_,"
}

$content = @"
package com.ithing.mobile.presentation.feature.dashboard

import androidx.compose.ui.graphics.vector.ImageVector
import com.composables.icons.lucide.*

// Generated by scripts/generate_dashboard_lucide_registry.ps1 from com.composables:icons-lucide.
private val DashboardLucideIcons: Map<String, ImageVector> = mapOf(
$($entries -join "`r`n")
)

internal fun dashboardLucideIcon(iconName: String?, fallback: ImageVector): ImageVector {
    val key = iconName.normalizeLucideIconKey()
    return DashboardLucideIcons[key] ?: fallback
}

private fun String?.normalizeLucideIconKey(): String =
    orEmpty()
        .trim()
        .lowercase()
        .filter { it.isLetterOrDigit() }
"@

Set-Content -Path $targetFile -Value $content -Encoding UTF8
Write-Host "Generated $($iconNames.Count) Lucide icons at $targetFile"
